a = ['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua']
a[0] = int(input("¿Qué nota has sacado en Matemáticas?"))
a[1] = int(input("¿Qué nota has sacado en Física?"))
a[2] = int(input("¿Qué nota has sacado en Química?"))
a[3] = int(input("¿Qué nota has sacado en Historia?"))
a[4] = int(input("¿Qué nota has sacado en Lengua?"))
print("En Matemáticas has sacado", a[0])
print("En Física has sacado", a[1])
print("En Química has sacado", a[2])
print("En Historia has sacado", a[3])
print("En Lengua has sacado", a[4])